spring.application.name=b01
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:23306/kosa_db
spring.datasource.username=root
spring.datasource.password=kosa1004

#\uc11c\ubc84 \ud3ec\ud2b8 \uc124\uc815
server.port=8380

#\uc11c\ubc84\uc758 \ucf54\ub4dc\uac00 \uc218\uc815\ub418\uba74 \uc790\ub3d9\uc73c\ub85c \uc11c\ubc84\uac00 \ub9ac\ub85c\ub4dc \ub41c\ub2e4
#\uc6b4\uc601\uc11c\ubc84 \ub9ac\ub85c\ub4dc 
spring.devtools.restart.enabled=true
#\uac1c\ubc1c\uc11c\ubc84 \ub9ac\ub85c\ub4dc
spring.devtools.livereload.enabled=true

logging.level.org.springframework=info
logging.level.kr.or.oti=info
logging.level.org.springframework.security=info

#Spring DATA JPA \uc124\uc815
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# \ucca8\ubd80\ud30c\uc77c \uc124\uc815
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=C:/upload
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB


spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me

spring.security.oauth2.client.registration.kakao.client-name=kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect_uri=http://localhost:8380/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-id=a145987d697c2488916fc281bcd4d8e3

spring.security.oauth2.client.registration.kakao.client-secret=cv32QcuRDjLBqzM6APO7oYKkp5mdR1bW
spring.security.oauth2.client.registration.kakao.client-authentication-method=POST
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,profile_image,account_email



